### ISSUE TITLE
Log for WF transition does not show complete path to object

### ISSUE THREAD

**Issue by gbastien** [collective/collective.fingerpointing#102]
Hi everybody,
I saw in the message logged when a transition something like :

`2020-01-15T10:41:39 INFO collective.fingerpointing user=myuser ip=1.2.3.4 action=workflow transition object=<Item at my-item-id> transition=publish`

the difference with other loggers is that object does not display the path to the object, it should be :

`object=<Item at /mysite/myfolder/my-item-id>`

is it OK to propose a PR regarding this?

Thank you!

Gauthier

**Comment by gbastien** [comment]
Hi @jensens @hvelarde 
that would be great to have a new release, do you think it is possible?
Thank you!!!
Gauthier

**Comment by hvelarde** [comment]
FYI: the Collective is now owner of this package on PyPI.
