### ISSUE TITLE
Lock file remains after instance stopped

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.fingerpointing#14]
I don't know if this is an issue:

```
# ls var/log/
audit.log  audit.log.lock  instance.log  instance-Z2.log
```

**Comment by frisi** [comment]
good question @hvelarde 
zc.lock is used for locking the zodb too. the Data.fs.lock file also remains after stopping zeo server properly. so i'd say its safe this way.

a way to try if everything works fine is to have two instances in a buildout using the same logfile.
start instance1 and do some actions that produce logs.
stop instance1, lock file should still be present
startup instance2
do some actions (login, edit/create content) that should end up in the log

if these actions are logged too, the remaining lock file should not do any harm.

@pcdummy can you confirm this please?

**Comment by hvelarde** [comment]
thanks! good to know
