### ISSUE TITLE
Event logging only on log level INFO

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.fingerpointing#25]
In production sites is a common pattern to set:

```
[instance]
event-log-level = ERROR
```

This will result on an empty audit log.

**Comment by hvelarde** [comment]
@frisi ideas?

**Comment by frisi** [comment]
good catch @hvelarde 

zope seems to set the log level of the root logger at startup and our audit.log logger inherits these settings.
luckily one can set the log level for each logger individually. 
done in #29
