### ISSUE TITLE
Exception when remove the Plone Site

### ISSUE THREAD

**Issue by rodfersou** [collective/collective.fingerpointing#4]
Steps to reproduce:
* Add a new plone site
* Get into ZMI
* Select and remove this plone site

    2015-06-17 10:06:51 ERROR Zope.SiteErrorLog 1434546411.90.276365361618 http://localhost:8080/manage_delObjects
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module OFS.ObjectManager, line 540, in manage_delObjects
      Module OFS.ObjectManager, line 408, in _delObject
      Module zope.event, line 31, in notify
      Module zope.component.event, line 24, in dispatch
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module zope.component.event, line 32, in objectEventNotify
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module OFS.subscribers, line 113, in dispatchObjectMovedEvent
      Module zope.container.contained, line 153, in dispatchToSublocations
      Module zope.component._api, line 136, in subscribers
      Module zope.component.registry, line 321, in subscribers
      Module zope.interface.adapter, line 585, in subscribers
      Module collective.fingerpointing.subscribers.lifecycle_logger, line 21, in lifecycle_logger
      Module plone.api.portal, line 2, in get_registry_record
      Module plone.api.validation, line 70, in wrapped
      Module plone.api.portal, line 238, in get_registry_record
      Module zope.component._api, line 169, in getUtility
    ComponentLookupError: (<InterfaceClass plone.registry.interfaces.IRegistry>, '')

**Comment by hvelarde** [comment]
seems easy to fix just by adding that exception [there](https://github.com/collective/collective.fingerpointing/blob/master/src/collective/fingerpointing/subscribers/lifecycle_logger.py#L19-L23):

```python
from zope.component import ComponentLookupError
...

    try:
        record = IFingerPointingSettings.__identifier__ + '.audit_lifecycle'
        audit_lifecycle = api.portal.get_registry_record(record)
    except (InvalidParameterError, ComponentLookupError):
        return
```
