### ISSUE TITLE
audit.log location

### ISSUE THREAD

**Issue by frisi** [collective/collective.fingerpointing#45]
according to the documentation the audit log should be created in `$BUILDOUT_DIRECTORY/var/log/audit.log`

when i add collective.fingerpointing to my buildout the logfile is created in `$BUILDOUT_DIRECTORY/bin/audit.log`

using 1.0b4

**Comment by hvelarde** [comment]
I never seen that behavior before and I have this add-on installed in more than a dozen sites; please investigate further.

**Comment by pcdummy** [comment]
This cause we have `MailingLogger` installed, with it installed the config looks like:

```xml
<eventlog>
  <mailing-logger>
  level error
  flood-level 5
  smtp-server localhost
  from sysadmin@webmeisterei.com
  to plone@webmeisterei.com
  subject Error-report [%(hostname)s-flytyrol-aviation] %(line)s
</mailing-logger>
  level INFO
  <logfile>
    path /home/zope/flytyrol-aviation/var/log/instance.log
    level INFO
  </logfile>
</eventlog>
```

Without:
```
<eventlog>
  level INFO
  <logfile>
    path /home/pcdummy/Projekte/webmeisterei/flytyrol-aviation/var/log/instance.log
    level INFO
  </logfile>
</eventlog>
```

Will come with a patch that fixes this soon.
