### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by gbastien** [collective/collective.fingerpointing#60]
Hi,

I would like to add french translations, I see there is no "fr" folder in locales, we used to run i18ndude to manage translations and add a synch_locales.sh file in locales to ease updates of various translations, could you please tell me how you proceed?  Can I add this helper .sh in locales?

Thank you,

Gauthier

**Comment by hvelarde** [comment]
I have added the files for you in a new branch; please feel free to proceed with the translations.

in the future you just have to run the included `bin/rebuild_i18n.sh` command that is generated using buildout.

**Comment by gbastien** [comment]
Hi @hvelarde 

great thank you, I will complete the branch so you can merge it.

Gauthier
