### ISSUE TITLE
Lifecycle logger: On create path is not logged.

### ISSUE THREAD

**Issue by jensens** [collective/collective.fingerpointing#66]
The life-cycle subscriber listens to ``zope.lifecycleevent.IObjectCreatedEvent``, but at this point the new object was not added to its container, so it shows no location:
```
2017-11-21 13:25:42 INFO collective.fingerpointing user=admin ip=127.0.0.1 action=create object=<Link at >
```
In order to show the location it should listen to ``zope.lifecycleevent.interfaces.IObjectAddedEvent``. After changing this in ``src/collective/fingerpointing/subscribers/lifecycle_logger.py`` (and its ``configure.zcml``) it shows the path like so:
```
2017-11-21 13:35:56 INFO collective.fingerpointing user=admin ip=127.0.0.1 action=create object=<Link at /Plone/newlink>
```

**Comment by hvelarde** [comment]
thank you for taking care of this; I had already noticed but had no time to implement the solution.
