### ISSUE TITLE
Enable audit log rotation

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.fingerpointing#9]
Audit log files can grow up quickly; we need to check Zope's code to implement log rotation in a similar way.

**Comment by frisi** [comment]
I'd say it's up to the system administrator to configure logrotate for the logfile.

**Comment by svx** [comment]
IMHO, I do not know, how other add-ons do that, but if other already do that, it may be an idea to include it.
If not, than it it up to the sysadmin.
In any case the README nor the /docs have a mention/note about either one, maybe it would be a good idea to add a note about log rotation, so that people are aware of it.

**Comment by hvelarde** [comment]
check the **Logging** section on [plone.recipe.zope2instance](https://pypi.python.org/pypi/plone.recipe.zope2instance):

```
event-log-max-size
    Maximum size of event log file. Enables log rotation.
event-log-old-files
    Number of previous log files to retain when log rotation is enabled. Defaults to 1.
...
access-log-max-size
    Maximum size of access log file. Enables log rotation.
access-log-old-files
    Number of previous log files to retain when log rotation is enabled. Defaults to 1.
```

**Comment by hvelarde** [comment]
in fact this is supported natively in Python using the [RotatingFileHandler](https://docs.python.org/2/library/logging.handlers.html#rotatingfilehandler) handler, and is very easy to implement.

**Comment by frisi** [comment]
@hvelarde yes - python logging is quite sophisticated ;-)

if we support rotating the log with RotatingFileHandler i think we should make it configurable (so people can use logrotate if they wish to) and disabled by default (so people do not wonder why they see just a few entries)

this would require to A) add control panel setting(s) i.e.
* "rotate log when it exceeds n megabytes" and
* "keep m old-files"

or B) use `environment-vars` in `plone.recipe.zope2instance` to configure these settings
